### ISSUE TITLE
Transformer les espaces en espaces insécables lorsque c'est nécessaire.

### ISSUE THREAD

**Issue by lypwig** [zestedesavoir/Python-ZMarkdown#100]
Cela pourrait être intéressant et faciliterait leur usage dans les contenus de ZdS.

Pour rappel, les espaces insécables permettent d'éviter les retours à la lignes à certains endroits ou cela gênerait la lecture et doivent être insérés :
- devant les signes `;`, `?`, `!`, `:` ;
- entre les signes `«` et `»` ;
- en tant que séparateur de milliers.

**Comment by cgabard** [comment]
@DominusCarnufex a une extension presque prête pour ça normalement.

**Comment by lypwig** [comment]
Cool ! Du coup ça va être mergé sur zmd-master ?

**Comment by cgabard** [comment]
Il faut qu'il fasse quelques changements, je ne sais pas où ça en est.

**Comment by DominusCarnufex** [comment]
C’en est là… https://github.com/zestedesavoir/Python-ZMarkdown/pull/102

**Comment by DominusCarnufex** [comment]
On peut fermer, #118 a réglé la question.
