### ISSUE TITLE
Emoji dans un message coupe le message jusqu'à l'emoji

### ISSUE THREAD

**Issue by vhf** [zestedesavoir/Python-ZMarkdown#103]
Pas sûr que ce soit un bug zmarkdown et pas ZdS, mais voici :

J'ai rédigé un MP et au milieu du MP j'ai flanqué un emoji. (J'ai simplement c/c celui-ci : http://emojipedia.org/octopus/)

Après avoir soumis le formulaire, le MP enregistré était le texte jusqu'à l'emoji, ce dernier non-compris. J'ai édité le MP pour voir ce qui se passait, le texte après l'emoji est simplement perdu.

Risque de perdre du contenu si le bug est dans zmarkdown, puisqu'on pourrait perdre par exemple  ce qu'on a rédigé dans un tuto ou un post si le contenu contient un emoji.

**Comment by SpaceFox** [comment]
C'est un problème connu et chiant : https://github.com/zestedesavoir/zds-site/issues/3416
