### ISSUE TITLE
Documenter comment faire tourner les tests

### ISSUE THREAD

**Issue by vhf** [zestedesavoir/Python-ZMarkdown#106]
J'ai tenté de reverse-engineerer comment faire passer les tests, mais j'y suis pas encore.

Voilà où j'en suis pour le moment : 

```
g co 2.6.0-zds.11
# installer les dépendances
pip install -r test-requirements.txt
# installer aspell
brew install aspell ou apt-get install aspell
# avoir un python2.7 nommé py27 dans son path
ln -s ~/.virtualenvs/zmd/bin/python ~/.virtualenvs/zmd/bin/py27
make build
make docs
make test
```

où j'en suis, j'ai 51 erreurs `ValueError: (tidylib) Config: unknown option: merge-spans`

J'ai aussi

```
Building docs...
skipping build_docs: Markdown "import" failed!
Compiling Dictionary...
Checking spelling...\n
find: build/docs/: No such file or directory
```

malgré le make docs

**Comment by firm1** [comment]
D'après [le code source](https://github.com/zestedesavoir/Python-ZMarkdown/blob/master-zds/.travis.yml#L10), il te manque tidy.

J'imagine que sur osx un `brew install tidy-html5` devrait fonctionner

**Comment by vhf** [comment]
Tiens je voulais justement regarder la config travis puis j'ai oublié, je me suis perdu en chemin. Avec tidy les tests passent, merci.

**Comment by cgabard** [comment]
En vrai les tests sont

**Comment by cgabard** [comment]
En vrai la suite de test est pourrie il faudrait la refaire mais bon... Il y a d'autres priorités (j'avance dessus d'ailleurs)
