### ISSUE TITLE
"Code:" en début de ligne est ignoré

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/Python-ZMarkdown#12]
Comme reporté ici :
http://zestedesavoir.com/forums/sujet/63/bug-reporte-mot-clef-code-ignore#p275

Une ligne qui commence par "Code:" (sans les quotes, forcément) se voit évincée de ce mot.

Il y a un exemple sur le topic si vous voulez du concret :)

**Comment by cgabard** [comment]
Oui ça je le savais et j'avais jamais prit le temps de le corriger. C'est pareil pour tous les noms de légendes.

**Comment by firm1** [comment]
Fixé
