### ISSUE TITLE
Renommer le packet Markdown -> ZMarkdown

### ISSUE THREAD

**Issue by vhf** [zestedesavoir/Python-ZMarkdown#129]
* Il semble que ce soit une bonne solution pour résoudre ceci : zestedesavoir/zds-site#4082
* #80 J'ai aussi l'impression que c'est nécessaire si on veut publier sur Pypi puisqu'un package `Markdown` y existe déjà
* Il me semble que c'est une opération assez anodine mais je peux me planter.

**Comment by GerardPaligot** [comment]
Cool, je me permets de relancer @cgabard pour savoir s'il a un avis sur cette issue.

**Comment by cgabard** [comment]
Je vais essayé de m'en occuper rapidement
