### ISSUE TITLE
[OK en fait] Item des listes pris en compte uniquement si on saute des lignes

### ISSUE THREAD

**Issue by amorison** [zestedesavoir/Python-ZMarkdown#15]
Lorsque l'on écrit une liste en Markdown en se contentant d'aller juste à la lgne pour séparer les items, ceux-ci ne sont pas pris en compte, on est obligé de sauter une ligne entre chaque item.

Ceci ne fonctionne pas :

```
blabla bla :
- item1
- item 2
- item 3
```

Il faut écrire:

```
blabla bla :
- item1

- item 2

- item 3
```

**Comment by cgabard** [comment]
J'ai répondu sur le forum. En fait non, il faut écrire normalement : 

```
blabla bla :

- item1
- item 2
- item 3
```

C'est entre le paragraphe d'avant et la liste que tout se joue. C'est le comportement de la majorité des implémentations markdown car le texte de référence dt clairement qu'il faut une ligne vide pour séparrer les différents blocs sémantiques (2 paragraphes, un paragraphe et une liste, etc.)

**Comment by amorison** [comment]
Ouais, OK, désolé pour la bourde... :-°
