### ISSUE TITLE
Lien de citation erroné

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/Python-ZMarkdown#16]
Il manque l'adresse du site devant l'adresse de la citation.
Actuellement le lien contient quelque chose comme "http://forums/sujet/13/test?page=1#p307"

Il manque zestedesavoir.com/

**Comment by cgabard** [comment]
En fait c'est le bouton "citation" du forum qui ne fait pas bien son taf. Il devrait mettre l'adresse aboslus puisqu'on m'a demandé de ne pas accepter les adresses relatives.

**Comment by cgabard** [comment]
Donc a rapporter sur le github de zds, je ferme ici.

**Comment by Alex-D** [comment]
C'est tout à fait exact, je viens de m'en rendre compte en citant quelqu'un ><"
