### ISSUE TITLE
Transformation en lien des adresses mail dans les posts

### ISSUE THREAD

**Issue by Coy0te** [zestedesavoir/Python-ZMarkdown#17]
Dans un post, les adresses mail sont censées être transformées automatiquement en lien `mailto` à l'affichage.

Cependant, il semble y avoir quelques soucis : 
=> http://zestedesavoir.com/forums/sujet/115/suggestionrapporte-interdire-les-adresses-email-temporaires?page=1#p1264

A priori, une adresse mail incomplète du type `@mail.com` est transformée. Par ailleurs, le lien généré est foireux (`http://mailto:...`)

**Comment by firm1** [comment]
Fixé.
