### ISSUE TITLE
Ajouter les tirets cadratins et demi-cadratins

### ISSUE THREAD

**Issue by SpaceFox** [zestedesavoir/Python-ZMarkdown#18]
C'est un truc de LaTeX à la base, que j'ai vu dans plusieurs implémentations de Markdown mais pas celui-ci :
- Deux signes moins `--` donnent un tiret demi-cadratin `–`
- Trois signes moins `---` donnent un tiret cadratin `—`

Bien entendu il n'y a aucune urgence ni impératif ici, c'est juste une idée d'amélioration si jamais quelqu'un s'ennuie un jour :)

**Comment by cgabard** [comment]
Il n'y a que ça ou d'autres ? J'avais vu une extension qui faisait plus (remplacer les guillemets, remplacer certains espaces insécables, etc.)...

**Comment by SpaceFox** [comment]
Les guillemets et autres, ça existe mais c'est plus délicat pour éviter les
interférences.

Et surtout très égoïstement c'est la principale fonctionnalité que
j'utilise :-)
Le 15 mai 2014 08:10, "Christophe Gabard" notifications@github.com a
écrit :

**Comment by cgabard** [comment]
Il faudra que je mette se parser en priorité basse, pour qu'il passe après les parseur de tableaux ou des titres soulignés et donc éviter les mauvaises interactions, mais en soit je ne vois pas d'objections ni de probs majeur avec ça
