### ISSUE TITLE
Smileys dans les blocs customs

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/Python-ZMarkdown#19]
Le code d'exemple est celui-là.

```
[[secret]]
| :-)
```

ou encore

```
[[s]]
| :waw:
```

Il fait planter le parseur.

**Comment by cgabard** [comment]
Je n'arrive pas a reproduire, il me faut la bt

**Comment by firm1** [comment]
Rahh il remarche, alors qu'il ne marchait pas quand j'ai posté l'issue. On dirait que la précédente résolution a résolu celui-ci
