### ISSUE TITLE
Smartlegend fait des siennes

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/Python-ZMarkdown#21]
L'article redidez sur zds donne une erreur 500.

J'ai réussi a trouver la backtrace, et et le problème vient de l'extension smartlegend qui semble détecter la chaine "source", mais ne sait pas quoi faire avec None.

Bref, j'ai l'envoie par mail a @cgabard

**Comment by cgabard** [comment]
Bon le parser ne plantera plus mais reste a voir si ça ne provoque pas de regressions

**Comment by cgabard** [comment]
a l'air fixé
