### ISSUE TITLE
Erreur de balise : figurecaption au lieu de figcaption

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/Python-ZMarkdown#23]
Les légendes sont affichées dans une balise `figurecaption` or celle-ci n'existe pas.

La bonne balise est `figcaption`

Merci d'avance, car du coup le design est cassé ^^

**Comment by cgabard** [comment]
OK c'est simple a corriger ça

**Comment by Alex-D** [comment]
Parfait !
