### ISSUE TITLE
Insertion de tweet

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/Python-ZMarkdown#24]
L'idée serait de pouvoir insérer des tweets via leur lien tweeter. Il faudrait aller faire une requête sur l'API Twitter pour récupérer le tweet en question et l'afficher sous forme d'une citation, mais avec un design particulier.

Voir la conversation sur l'autre dépôt pour plus d'informations : https://github.com/Taluu/ZesteDeSavoir/issues/535

Une structure HTML comme celle-ci me semble fort sympathique :

```
<figure class="tweet">
    <figcaption><a href="https://twitter.com/AlexandreDemode">Alex-D</a> à <a href="https://twitter.com/AlexandreDemode/<ID_TWEET>">HH:mm:ss</a></figcaption>
    <blockquote>
        Le message du tweet qu'il est beau ici
    </blockquote>
</figure>
```

**Comment by firm1** [comment]
Moi j'aurai dis le même rendu HTML que pour les citations avec pour seule
différence la classe tweet.
 Le 22 mai 2014 14:40, "DEMODE Alexandre" notifications@github.com a
écrit :

**Comment by Alex-D** [comment]
Ca ne change pas grand chose, tant qu'à faire de taper l'API autant récupérer les infos et avoir une structure dédiée.

**Comment by cgabard** [comment]
Perso au lieu de mettre un liens vers ton profil j'aurais plutot mis le liens vers le tweet directement.

**Comment by firm1** [comment]
Je reprends donc ce que je disais : actuellement une citation rend ceci : 

``` html
<figure>
<blockquote>
<p>Mon super texte de citation</p>
</blockquote>
<figcaption><a href="http://zestedesavoir.com">Moi</a></figcaption>
</figure>
```

l'idée c'est donc qu'un tweet rende ceci : 

``` html
<figure>
<blockquote>
<p>Mon super texte de tweet</p>
</blockquote>
<figcaption><a href="http://url/du/tweet">Moi à 12h00</a></figcaption>
</figure>
```

On garde la même structure car on en fera certainement aussi un jour pour un autre réseau social.

**Comment by cgabard** [comment]
Oui. Enfin vous avez encore le temps de vous engeuler, j'ai pas une grosse motivation pour l'insérer tout de suite ça de toute façon...

**Comment by Alex-D** [comment]
Vas pour ça si vous voulez... je m'en fou au fond, juste y aura un fond bleu à la twitter et tout le monde sera content.

**Comment by cgabard** [comment]
De toute façon moi c'est pas trop mon prob, le gros du boulot de présentation sera au front

**Comment by Alex-D** [comment]
Si on suit le raisonnement de @firm1 y a rien qui change par rapport à une blockquote classique si ce n'est une couleur de fond ou une bordure quoi... c'est pas violent.

**Comment by cgabard** [comment]
Oui enfin je rajouterais une class tout de même, tu en fera ce que tu voudras

**Comment by SpaceFox** [comment]
Personnellement j'ai toujours pas compris à quel moment Twitter était
devenu tellement intéressant que pour un site comme le nôtre, on en est
arrivé à la conclusion que "ha tiens, ce serait cool d'avoir une
intégration spécifique pour Twitter, ça a une super valeur ajoutée".

Après, si quelqu'un est motivé par la fonctionnalité, je ne vais pas
l'empêcher de la développer.
C'est juste que ça me paraît absurde.

2014-05-22 16:34 GMT+02:00 Christophe Gabard notifications@github.com:

**Comment by cgabard** [comment]
Comme je le disais, je n'ai pas l'intention de le faire de toute suite de toute façon. Et ce sera sous forme d'une extension donc activable dans zds au besoin.

**Comment by firm1** [comment]
Elle n'est pas prioritaire du tout, mais je pense qu'elle peut servir dans des articles pour citer quelqu'un

**Comment by cgabard** [comment]
Fermé coté Zds, mériterai une zep maintenant, je ferme
