### ISSUE TITLE
Comportement bizarre des formules bloc maths

### ISSUE THREAD

**Issue by Taluu** [zestedesavoir/Python-ZMarkdown#26]
Quand on met une formule entre `$` (type `$a + b = c$`), ca passe et ca rend bien.

Mais si on a plusieurs lignes, type

``` latex
$\begin{array} {lcl}
    \text{borne droite} - \text{borne gauche} & = & 4 - 3 \\\ 
                                              & = & 1     \\\ 
                                              & = & 0 + 1 \\\ 
                                              & = & \boxed{0} \times 2  + 1
\end{array}$
```

Autant la balise maths est bien reconnue, mais on se retrouve avec des `$` avant et après la formule.

Au passage, il semblerait que la syntaxe de pdp `\\( formule, block ou inline \\)` passe crème elle. Quand j'en ai parlé à @firm1, il a dit que ça avait l'air chelou que cette syntaxe soit acceptée...

Lié à zestedesavoir/zds-site#719

**Comment by Taluu** [comment]
s/normale/chelou que cette syntaxe soit acceptée

**Comment by cgabard** [comment]
en fait pour les formule multilignes, non inline donc, il faut utiliser les doubles $$. C'est normal qu'avec les simples ça ne marche pas.

Pour la deuxième syntaxe, c'est un effet de bord. En fait la syntaxe n'est PAS reconnu par markdown mais l'est par mathjax. Donc si le contenu de ta balise math n'a rien de markdown, pas de soucis le contenu n'est pas modifié et mathjax peut le transformer.

Par contre si tu as du contenu interprétable par markdown dedans, ça casse tout.

demo : http://zestedesavoir.com/forums/sujet/235/test-math/

Donc : 
- Pas de bug au niveau markdown, tu as juste pas utilisé la bonne balise pour les formules multilignes.
- Sur zds il faut créer un ticket pour virer le support de la deuxième notation dans mathjax
- Ça participe probablement au blocage de transformation de ton tuto. Utilise les doubles dollars et ça devrait etre bon.
