### ISSUE TITLE
[CI] Implement Travis

### ISSUE THREAD

**Issue by Taluu** [zestedesavoir/Python-ZMarkdown#3]
Implémenter travis pour faire des tests lors des push pour une intégration continue ?

**Comment by cgabard** [comment]
J'y pense mais en fait j'attends que le projet upstream le fasse. Il a commencé a le mettre en place mais pour l'instant ça ne passe pas. Je vais donc attendre qu'il corrige lui même pour le basculer ici, ce sera beaucoup plus simple.

En attendant il faudrat que je rajoute des tests sur nos codes

**Comment by Alex-D** [comment]
Vu que ce dépôt va commencer à corriger les bugs et autres, ça serait pas mal que les tests et le Travis soient mis en place :)

À noter qu'il a été désactivé sur le projet upstream pour l'instant (dépassement de quota).

**Comment by cgabard** [comment]
2 ans après, je ferme
