### ISSUE TITLE
Ajout d'une classe sur les minicodes

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/Python-ZMarkdown#30]
Pour pouvoir corriger certains bugs d'affichage, il faudrait rajouter une classe sur la base `<code>` utilisée pour du "minicode" (`code-inline` par exemple).

Le soucis d'affichage est visible dans les citation car on a

```
figure > blockquote > code
```

Or pour une balise code légendée on a

```
figure > code
```

Du coup, c'est plus délicat à gérer s'il n'y a pas la classe qui va bien (la balise code étant dans les deux cas dans une balise figure)

**Comment by firm1** [comment]
Il y'a forcément un moyen de styliser ça en css (`>`, `~`, etc.) en évitant de rajouter de la complexité à zmarkdown.

**Comment by Alex-D** [comment]
Le soucis viens dans les citations imbriquées.

```
figure > blockquote > blockquote > code
```

Du coup, c'est pas vraiment gérable en CSS j'ai l'impression.

**Comment by cgabard** [comment]
Si il n'y a que ça, je devrais pouvoir le faire même si ça va me faire faire quelques hack pas beaux. Mais je comprend pas trop pourquoi avant ça passait. Bref.

**Comment by firm1** [comment]
Pour moi, si ça passait avant en css, ça devrait pouvoir passer maintenant en css. Si on commence a toucher a zmarkdown (un projet à part entière) pour résoudre des problèmes css, on est pas sorti.

C'est comme l'histoire du `ico-after`, c'est en parcourant les codes scss que je me suis rendu compte qu'on pouvait l'éviter ... m'enfin, c'est déjà implémenté

**Comment by Alex-D** [comment]
Finalement inutile.
