### ISSUE TITLE
Avoir un paramètre permettant la génération d'ancres sur les titres.

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/Python-ZMarkdown#31]
L'idée serait d'avoir des `id` sur les titres, seulement si le paramètre le demande.

Pourquoi un paramètre ?

Si on le fait tout le temps, sur les forums par exemple on peut se retrouver avec plusieurs fois le même titre et donc le même id et donc c'est invalide.

Aussi, il faut désactiver cette fonctionnalité à l'intérieur des citations.

**Comment by cgabard** [comment]
Alors pour les probs de forum, en fait on a déjà le prob avec les notes de bas de page. Je pense que le markdown va recevoir a terme un id/prefix qui sera utilisé pour les notes de bas de pages. On pourrait réutiliser le même pour les titres. Du coup ça peut etre activé systématiquement. Mais en effet il faut le désactiver dans les citations.

**Comment by cgabard** [comment]
(Quoique dans une citation, il sera pré-fixé par l'id du post qui fait la citation, pas celui de base, donc aucun soucis a priori)

**Comment by Alex-D** [comment]
Ah oui, pas bête du tout, du coup ça me paraît bien :)

**Comment by cgabard** [comment]
Réglé par #121
