### ISSUE TITLE
Liens mal parsé

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/Python-ZMarkdown#35]
Certains liens sont mal parse. Normalement, si les balises markdown ne sont pas utilise de maniere explicite, un lien est tout de meme reconnu et interprete comme tel. Cependant, cela ne semble pas fonctionner si le lien possede des parametres et/(ou ?) eventuellement une ancre)

Exemple (qui marche bien sur GH):
NOK : http://zestedesavoir.com/forums/sujet/429/fin-de-la-beta-privee/?page=1#p4205  
NOK : http://zestedesavoir.com/forums/sujet/429/fin-de-la-beta-privee/?page=1  
OK : http://zestedesavoir.com/forums/sujet/429/fin-de-la-beta-privee/

**Comment by cgabard** [comment]
Pour le corriger : aller mettre a jour les re ici : https://github.com/zestedesavoir/Python-ZMarkdown/blob/master-zds/markdown/extensions/urlize.py#L43

**Comment by cgabard** [comment]
(en attendant il est possible d'utiliser la syntaxe normal des liens (`[mon sujet](ton lien)`) ou la syntaxe à base de `<..>` : `<http://zestedesavoir.com/forums/sujet/429/fin-de-la-beta-privee/?page=1#p4205>` fonctionne sur zds)

**Comment by Eskimon** [comment]
Je connaissais pas la seconde syntaxe, good to know !
Par contre je reportais justement parce quand je veux juste balancer un lien, c'est pratique d'avoir le linkage auto ;)

**Comment by ArnaudCalmettes** [comment]
Je prends, pour me faire la main.

**Comment by cgabard** [comment]
NB : les tests ne passent pas, c'est normal.

Nb2 : une fois op, il faut refaire un commit pour changer le numéro de
version (dans le fichier **version**.py ou **init**.py je ne sais plus)
puis taguer la nouvelle version sur github (onglet release ou un truc du
genre) puis aller faire un commit+pr sur zds-site en mettant a jour le
requierement.txt avec la nouvelle version.
Le 27 juin 2014 20:22, "ArnaudCalmettes" notifications@github.com a écrit
:

**Comment by ArnaudCalmettes** [comment]
Euh... OK. 
Je suppose que j'en profiterai pour documenter le workflow le jour où j'aurai réussi ma première PR.

**Comment by cgabard** [comment]
Desole

Il faut taguer la version sur git/github pour que le fichier de dépendance
du site pointe sur la bonne version.

Je me suis a mettre a jour le numéro de version utilisé par le setup.py en
correspondance pour que les contributeurs récupèrent bien la dernière
version en faisant leur "pip install --update" ce qui est la mise a jour
préconisé sur le projet. Sinon les qa n'auraient pas forcément la dernière
version.
Le 27 juin 2014 20:47, "ArnaudCalmettes" notifications@github.com a écrit
:

**Comment by ArnaudCalmettes** [comment]
D'accord, j'ai pigé. Merci pour la précision.

**Comment by cgabard** [comment]
normalement, fixé dans zmarkdown.

**Comment by firm1** [comment]
La version est taggué ?

**Comment by cgabard** [comment]
Non, je le ferais avant la beta. Inutile pour le moment de taguer chaque
correction de bugs

Christophe.

**Comment by Eskimon** [comment]
J'ai un nouvel exemple de lien qui marche pas, l'ancre avec un tiret :
`https://github.com/zestedesavoir/zds-site/issues/862#issuecomment-48449562`
