### ISSUE TITLE
Video plantage markdown

### ISSUE THREAD

**Issue by cgabard** [zestedesavoir/Python-ZMarkdown#38]
cf exemple http://zestedesavoir.com/forums/sujet/521/apercu-post-en-publiant-un-lien-youtube/?page=1

**Comment by Eskimon** [comment]
Second exemple : http://zestedesavoir.com/forums/sujet/627/cache-cache-de-texte-avec-les-videos/

**Comment by sandhose** [comment]
Mergé, à fermer

**Comment by Eskimon** [comment]
NON ! Ca bug toujours, il ne faut pas fermer.

https://github.com/zestedesavoir/zds-site/pull/1207#issuecomment-49352235

**Comment by cgabard** [comment]
Ne pose plus de prob en prod, je ferme
