### ISSUE TITLE
Problème de smileys et fin de ligne

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/Python-ZMarkdown#39]
Le cas d'usage : 

```
Tant mieux :)  
Je suis content que cela te plaise.
```

Si on mets un smiley en fin de ligne suivi de 2 espaces, le smileys ne s'affiche pas.

Plus d'informations [ici](http://zestedesavoir.com/forums/sujet/613/smileys-et-nouvelle-ligne/)

**Comment by sandhose** [comment]
Mergé, à fermer
