### ISSUE TITLE
Problème avec les tableaux.

### ISSUE THREAD

**Issue by sylafrs** [zestedesavoir/Python-ZMarkdown#44]
https://github.com/zestedesavoir/zds-site/issues/1251

J'explique l'issue sur le site Zeste de Savoir ici : http://zestedesavoir.com/forums/sujet/748/tableaux-la-fusion-de-cellules-verticale-en-fin-de-ligne/

Lorsque le rowspan se trouve à la dernière colonne, cela n'est pas parsé.
Lorsqu'il se trouve au milieu : une case est 'oubliée'

En fait je crois qu'il 'saute' la cellule de la ligne la plus à gauche dans tous les cas de figure.

Je me doute que vous le savez, mais le fichier est là : https://github.com/zestedesavoir/Python-ZMarkdown/blob/master-zds/markdown/extensions/grid_tables.py

(J'ai du mal à lire le python, faudrait que j'apprenne ^^ )

**Comment by cgabard** [comment]
Je vais vois mais cette extension est assez capricieuse. 

Le prob aussi est que Pandoc ne prend pas en charge les fusions et donc on va avoir des prob a l'export. Je me demande si le mieux ne serait pas juste de le virer.

**Comment by cgabard** [comment]
Un peu tard mais la versionne actuel du markdown corrige le problème.
