### ISSUE TITLE
Parsing automatique d'URL incorrect.

### ISSUE THREAD

**Issue by karlyeurl** [zestedesavoir/Python-ZMarkdown#46]
Le parsing automatique d'URL est un peu trop gourmand, comme le montre [ce post](http://zestedesavoir.com/forums/sujet/890/ou-habitent-nos-zesteurs/?page=4#p14137), où le lien renvoie vers http://mappemonde.net./ (notez le point final).

Je ne suis, d'ailleurs, pas certain de la pertinence de rendre machin.truc cliquable. Si ça commence par www. ou http://, oui, mais sans, non.

**Comment by SpaceFox** [comment]
Le problème est que de plus en plus de navigateurs font sauter les
http[s]:// quand on copie l'URL, surtout sur mobile :(

**Comment by karlyeurl** [comment]
Le deuxième point est une question de préférence personnelle, et je peux comprendre qu'il y a des raisons pour lesquelles ce comportement est désiré (je le trouve simplement inutile et parfois incommodant). Ce n'est pas vraiment important, mais des solutions peuvent être discutées (j'ai quelques idées sur la question).

En revanche, le premier point que je mentionne est la raison pour laquelle j'ai ouvert ce report de bogue, car il s'agit vraiment d'un comportement qui n'est pas souhaitable.

**Comment by cgabard** [comment]
Normalement le parse automatique ne fonctionne que si il y a le protocole (http(s)/ftp) OU si l'url semble avoir un patern tres commun ( "www." + nom + ".fr|com|net|org" + ...). Donc normalement l'absence de protocole n'entraine un lien que dans des rares cas.

Pour le . a la fin de ton liens, je vais voir ça...

**Comment by cgabard** [comment]
C'est maintenant corrigé de notre coté !
