### ISSUE TITLE
Liens vers les fiches de Wikimedia non reconnus

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/Python-ZMarkdown#47]
Bug reporté depuis `zds-dev` [zds-dev#1351](https://github.com/zestedesavoir/zds-site/issues/1351)

Message de @Florianboux :

> Je l'ai [signalé sur le forum](http://zestedesavoir.com/forums/sujet/984/les-liens-vers-wikimedia-ne-fonctionnent-pas/?page=1#p15299) pour que la visibilité soit maximal, mais je viens aussi le signaler ici.
> 
> Les liens vers les **fiches** détaillées du Commons de Wikimedia, ne fonctionnent pas.
> 
> Par-exemple ce genre d'URL ne passe pas : `http://commons.wikimedia.org/wiki/File:Swallow_flying_drinking.jpg`
> 
> À mon avis, zMD aimerait l'afficher en image, mais ne comprend pas que c'est un lien et non une image du fait que Wikimedia mettent l'extension de cette dernière à l'URL.

---

Mon avis sur la question est que le `:` fais suer.

**Comment by cgabard** [comment]
Doublon de #50 plus complet, je ferme
