### ISSUE TITLE
Tutoriel ne s'ouvre pas

### ISSUE THREAD

**Issue by Richard-Degenne** [zestedesavoir/Python-ZMarkdown#48]
**Configuration** :
- **OS** : Mac OS X 10.9.4
- **Python** : 2.7.5 ou 3.1
- **Java** : 1.7.0_65

Lorsque j'essaie d'ouvrir mon tutoriel (actuellement en cours de rédaction), rien ne se passe. Cependant, lorsque je tente d'ouvrir un tutoriel en ligne (J'ai essayé avec [celui-ci](http://zestedesavoir.com/tutoriels/441/pourquoi-vous-devriez-avoir-une-peluche-sur-votre-bureau/)), tout fonctionne correctement.

**Comment by SpaceFox** [comment]
A mon avis, ce n'est pas le bon projet.

Je suppose que tu parles de [l'éditeur hors-ligne](http://zestedesavoir.com/forums/sujet/1003/editeur-offline-pour-les-tutoriels-de-zds/) de @firm1  ?

**Comment by firm1** [comment]
Je crois que @SpaceFox a raison, tu es sur le mauvais projet.

Je t'invite à aller poster ton issue [le bon projet](https://github.com/firm1/zmarkdown-editor), même si je pense que mon précédent commit la résolu.

Cette issue est à fermer donc.
