### ISSUE TITLE
Bug de rendu des boutons dans une liste

### ISSUE THREAD

**Issue by Axylium** [zestedesavoir/Python-ZMarkdown#49]
C'est déjà connu, mais c'est souvent remonté, donc j'ouvre tout de même une issue ici, puis ça permettra d'avoir un suivi. 

Via @mlorant sur le repo `zestedesavoir/zds-site` : 

> Lorsque j'écris des boutons type `<kbd>` dans une liste, le rendu simule un tableau illisible :
> 
> Extrait :
> 
> ``` text
> - ||Ctrl-B|| pour mettre en gras (fait apparaitre `** **`)`
> - ||Ctrl-I|| pour mettre en italique (fait apparaitre `* *`)
> - ||Ctrl-L|| pour ouvrir le pop-in d'ajout de liens
> - ||Ctrl-K|| pour indenter un bloc (très utile en cas de sélection)
> - D'autres exemples peuvent être visible sur [cette page de S.O](http://stackoverflow.com/questions/ask), mais les plus utiles sont là.
> ```
> 
> Résultat :
> ![](https://cloud.githubusercontent.com/assets/532337/3889815/8d58d55e-2215-11e4-9451-c0fa6b897cef.PNG)

**Comment by cgabard** [comment]
Tiens je n'avais jamais vu... Malheureusement on semble avoir une collision de syntaxe, je ne sais pas trop comment on va pouvoir régler ça... Peut être en simplement demandant aux listes d'être parsés avant les tableaux

**Comment by cgabard** [comment]
[En cours de merge](https://github.com/zestedesavoir/zds-site/pull/2291), probablement sur la 1.7 (ou 2.0) de zds. Je ferme car c'est réglé coté markdown.
