### ISSUE TITLE
Le parseur markdown ne reconnaît pas les URLs contenant des `:`

### ISSUE THREAD

**Issue by gasche** [zestedesavoir/Python-ZMarkdown#50]
J'ai essayé de poster l'[adresse suivante](https://gitorious.org/gasche-snippets/anagram-path/source/aa16730b68cec4f7e13fd09a68cdc0dc1f98d787:defi.ml) sur un topic du ZdS. Mon message bien été renvoyé mais l'URL a été remplacée par `http:///`, rendant le lien invalide. Le problème vient des deux points au milieu de l'URL (pourtant valides), car utiliser manuellement leur encodage `%3A` à la place fait ré-apparaître l'URL.

Il est problématique que zds-markdown ne gère pas cette URL, mais encore plus gênant que je n'ai pas été prévenu de cette perte d'information au moment de la prévisualisation ou envoi du message (sinon j'aurais pu contourner au moment de l'écriture, au lieu d'apprendre quelques jours après que tous les liens sont en fait morts).

**Comment by Axylium** [comment]
C'est connu. Du moins, j'ai déjà ouvert une issue (https://github.com/zestedesavoir/Python-ZMarkdown/issues/47). Mais cette fois-ci avec les URL des fiches Wikimédia.

**Comment by cgabard** [comment]
> Il est problématique que zds-markdown ne gère pas cette URL, mais encore plus gênant que je n'ai pas été prévenu de cette perte d'information au moment de la prévisualisation ou envoi du message

Tout a fait. Je ne me suis pas encore penché sur le problème mais en fait c'est la première fois que ce type de problème apparait. Avant cela les problèmes que nous avions eu concernant les liens étaient dut à l'extension générant les liens autos. Le problème était facilement visible puisque ces liens n'étaient pas inséré.

Ici le problème est autre, le liens est visible mais l'adresse vide. Je n'ai actuellement aucune idée d'où cela peut venir mais je soupsonne un bug upstream en l'occurence, dans python-markdown sur lequel nous nous basons.

**Comment by cgabard** [comment]
(bon a premiere vue cela semble etre un bug specifique, reste à comprendre pourquoi)

**Comment by bendia-** [comment]
Bonjour

Je vois quelque chose dans par là _markdown / inlinepatterns.py_ ligne 368, dans la méthode _sanitize_url_ qui pourrait être responsable

``` python
for part in url[2:]:
    if ":" in part:
    # A colon in "path", "parameters", "query" or "fragment" is suspect.
        return ''
```

**Comment by cgabard** [comment]
En effet. Ce qui est étrange c'est que sur [babelmark2](http://johnmacfarlane.net/babelmark2/), Python-Markdown ne semblait pas faire ce genre de changement (ce qui me faisait penser à un prob de nos extensions).

Je vais tenter de regarder ça ce week end. Par contre je n'ai pas la moindre idée des conséquences qu'il peut y avoir à virer ça. Et en quoi un `:` est supect. La solution peut venir d'un encodage automatique des `:` en `%3A`

**Comment by bendia-** [comment]
Voilà pourquoi `:` peut être suspect, on peut executer du code javascript comme ça

``` html
    <a href="javascript:alert('XSS');"> Cliquez ici </a>
```

Du coup, l'idée d'encoder `:` en `%3A` est bonne, même si ça fait étrange à la lecture.

**Comment by cgabard** [comment]
[En cours de merge](https://github.com/zestedesavoir/zds-site/pull/2291), probablement sur la 1.7 (ou 2.0) de zds. Je ferme car c'est réglé coté markdown.

**Comment by gasche** [comment]
Merci !

**Comment by cgabard** [comment]
Désolé surtout pour le temps de correction un peu long...
