### ISSUE TITLE
les footnotes entrent en conflit si la meme page a plusieurs appels au parseur (unicité des footnotes)

### ISSUE THREAD

**Issue by Nodraak** [zestedesavoir/Python-ZMarkdown#51]
Une [issue sur zds-site](https://github.com/zestedesavoir/zds-site/issues/1164) a donné lieu a une proposition de [hack pas propre](https://github.com/zestedesavoir/zds-site/pull/1399/files#diff-357416f7359afef7a8915d076461dad1R56).

Par défaut, l'extension _footnotes_ propose un paramètre `UNIQUE_IDS` pour activer un id unique (sous la forme d'un compteur, [incrémenté](https://github.com/zestedesavoir/Python-ZMarkdown/blob/master-zds/markdown/extensions/footnotes.py#L91) a chaque appel au parseur). Pour l'utiliser il faudrait alors garder la meme instance du parseur (impossible : maj du code, crash du serveur, ...) ou pouvoir réinitialiser cet id a la valeur que l'on veut.
La question est donc : peut on passer des options via l'extension zds, qui la transmettrais a _footnotes_. (du code à ajouter [quelque part par là](https://github.com/zestedesavoir/Python-ZMarkdown/blob/master-zds/markdown/extensions/zds.py#L107) à premiere vue). Si non, il faudrait activer l'extension _footnote_ a pars, comme ca :

``` diff
zds/utils/templatetags/emarkdown.py
@@ -12,10 +12,17 @@

 # Markdowns customs extensions :
-def get_markdown_instance(Inline=False):
+def get_markdown_instance(Inline=False, unique_id=''):
     zdsext = ZdsExtension({"inline": Inline, "emoticons": smileys})
+
+    extension_configs = {'footnotes':
+                       [
+                          ('UNIQUE_IDS', str(unique_id))
+                       ]
+                    }
     # Generate parser
-    md = markdown.Markdown(extensions=(zdsext,),
+    md = markdown.Markdown(extensions=(zdsext, 'footnotes'),
+                           extension_configs=extension_configs,
                            safe_mode = 'escape',
                            # Protect use of html by escape it
                            enable_attributes = False,
```

D'éventuelles autres idées, des questions, des suggestions ?

**Comment by cgabard** [comment]
Oui c'est possible. Et en fait il n'y a pas que les notes de bas de pages de concernés, il y a aussi les titres qui devraient avoir des ancres uniques (cf. https://github.com/zestedesavoir/Python-ZMarkdown/issues/31 )

Faut que je m'y attele mais je n'ai pas beaucoup de temps en ce moment :(

**Comment by cgabard** [comment]
Réglé par #121
