### ISSUE TITLE
Source mal parsee

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/Python-ZMarkdown#53]
Si j'ecris un smiley apres une citation sans source, ce dernier passe en source...

Par exemple:

```
> du texte que je cite

:D Ceci n'est pas une source !
```

Me donnera:

![screenshot from 2014-10-28 08 38 58](https://cloud.githubusercontent.com/assets/761168/4804937/8123946c-5e75-11e4-9f5f-e1f2ed0b12ee.png)

**Comment by cgabard** [comment]
Yep parce que tu as le droit d'oublier le mot "Source" avant les `:`
