### ISSUE TITLE
Permettre le support des URL relatives

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/Python-ZMarkdown#54]
Un lien sous la forme `/truc/machin` doit être conservé tel quel dans le lien :

```
<a href="/truc/machin">
```

Sans lui rajouter `http://` devant.

**Comment by cgabard** [comment]
Il faut fouiller les tickets mais on m'avait demandé l'inverse (entre autre pour que les gens qui écrivent "google.fr" sans tout le bordel devant aient un lien correct.

**Comment by Alex-D** [comment]
Il faut check si ça commence par un / ou non. Si oui, c'est une relative, sinon une absolue et pour le coup on rajoute bien le http:// :)

**Comment by cgabard** [comment]
[En cours de merge](https://github.com/zestedesavoir/zds-site/pull/2291), probablement sur la 1.7 (ou 2.0) de zds. Je ferme car c'est réglé coté markdown.
