### ISSUE TITLE
Échaper les pseudos

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/Python-ZMarkdown#58]
Via [__forever sur le forum](http://zestedesavoir.com/forums/sujet/1791/pseudo-compile-en-markdown-dans-les-messages/?page=1#p31563) : 

> Comme vous le voyez sûrement, mon pseudo est __forever, le problème est que __ signifie gras en Markdown, ce qui fait que j'ai reçu un message comme sa:
> 
> ![Capture d'écran d'un message de Clem](http://zestedesavoir.com/media/galleries/1140/777a3bc5-c970-4cd9-bd1e-5607d02a083e.png.960x960_q85.png)
> 
> On peut voir que mon pseudo est intégré au message, pour que ensuite le message soit compilé en html. Il manque donc simplement des `\` devants les caractères _spéciaux_.

**Comment by cgabard** [comment]
Ce n'est pas un ticket de zmarkdown (donc je vais le fermer). Le site passe le message au format markdown, ici on a aucun moyen de savoir que c'est un pseudo. C'est au site d'échapper les caractères spéciaux.
