### ISSUE TITLE
Erreur en prévisualisant un message dans ZdS

### ISSUE THREAD

**Issue by lthms** [zestedesavoir/Python-ZMarkdown#60]
Je suis bête et méchant, alors je fais ce que le site me dit, à savoir : 

> Une erreur est survenue dans la génération de texte Markdown. Veuillez rapporter le bug.

Le texte qui provoque cette erreur : 

```
> Personne ne s'accordait vraiment sur la nature de la fin du monde. Guerre nucléaire, jugement dernier, météorite insoupçonnée, les théories allaient foison, mais finalement, tout s'est passé en... douceur. C'est ce qui s'est passé après qui a été mouvementé.
> [source]: Test
```

**Comment by GerardPaligot** [comment]
Après des tests, il s'agit du chevron devant `[source]: Test` qui fait merder la génération du markdown.

@lethom : Pour information, les sources s'ajoutent sans crochet, sans chevron et avec un "s" majuscule.

```
> Citation
Source: Auteur de la citation
```

**Comment by lthms** [comment]
Yep, j'ai été voir dans le tuto ZdS avant de poster l'issue. Mais y avait l'ordre impérieux en rouge et tout alors j'ai été poster quand même ;o.

**Comment by cgabard** [comment]
Indeed. Ton bout de message n'est pas au format valide mais ce n'est pas normal qu'il fasse planter le markdown. Je regarderai ça

**Comment by lthms** [comment]
> Ton bout de message n'est pas au format valide mais ce n'est pas normal qu'il fasse planter le markdown.

C'est en effet le raisonnement que j'ai pu avoir. Bon courage pour le _debug_, en tout cas.
