### ISSUE TITLE
  Rendre les tableaux et les formules MathJax responsives

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/Python-ZMarkdown#61]
Actuellement, les tableaux et les formules MathJax (celles _displayed_, c'est-à-dire en `$$ $$`) causent https://github.com/zestedesavoir/zds-site/issues/2001 quand ils sont trop long en largeur.

Il faudrait les englober, avec par exemple ça :

``` html
<div class="table-wrapper">
    <!-- Le tableau -->
</div>
```

``` html
<div class="mathjax-wrapper">
    <!-- La formule MathJax -->
</div>
```

**EDIT :** Le css est prêt sur [ma branche "responsive-table-mathjax"](https://github.com/Situphen/zds-site/tree/responsive-table-mathjax) dont les changements sont visibles [ici](https://github.com/Situphen/zds-site/compare/responsive-table-mathjax).

**Comment by cgabard** [comment]
Ok, je vais essayé de faire ça et je te pinguerai quand je proposerai la nouvelle version du markdown pour que tu t'occupe de mettre a jour le css au passage

**Comment by Situphen** [comment]
Merci :)

**Comment by cgabard** [comment]
[En cours de merge](https://github.com/zestedesavoir/zds-site/pull/2291), probablement sur la 1.7 (ou 2.0) de zds. Je ferme car c'est réglé coté markdown.
