### ISSUE TITLE
Problème d'alignement avec le markdown

### ISSUE THREAD

**Issue by ghost** [zestedesavoir/Python-ZMarkdown#62]
Bonjour,

Il y a un problème d'alignement, lorsque deux centrages sont séparés par un alignement à droite. 

```
-> center <-

-> right ->

left

-> center <-
```

On obtient ceci :

> <div align=center>

center

right ->

left

-> center
</div>

**Comment by cgabard** [comment]
Ouais mais c'est assez compliqué à régler vu la nature de la syntaxe. Python-Markdown n'est structurellement pas du tout fait pour gérer ce genres de marqueurs de délimitation de blocs. De plus notre syntaxe est a la limite de l'ambiguïté sur ce coup. Je peux voir pour améliorer ce comportement mais ça me semble loin d'etre évident proprement

**Comment by cgabard** [comment]
Il s'agit surtout ici d'un problème de syntaxe ambiguë donc difficile d'avoir une bonne réponse. Avant de fermer il faut que je vérifie comment est réglé la regexp, on peut voir pour la forcer à s'arreter le plus to possible au lieu de la fin ici

**Comment by cgabard** [comment]
Fixé, bientot sur zds
