### ISSUE TITLE
Mauvaise url dans un lien si le titre du lien est une (autre) url

### ISSUE THREAD

**Issue by sandhose** [zestedesavoir/Python-ZMarkdown#65]
[via forum](https://zestedesavoir.com/forums/sujet/2771/une-petite-question-de-css/#p50242)

Quand on poste un lien, avec dans le titre du lien quelque chose qui ressemble à une url, ça utilise le titre du lien comme href, plutôt que le lien donné... Exemple: `[google.com](http://google.com/maps/)` va donner un lien vers `http://google.com`, alors que ça devrait donner un lien vers `http://google.com/maps/`

Je suppose que c'est un bug à transmettre à l'upstream ?

**Comment by viki53** [comment]
En fait ça donne un lien dans un lien, pour être plus précis : 

``` mardown
[jsfiddle.net](http://jsfiddle.net/naqE6/938/)
```

Donne donc : 

``` html
<a href="http://jsfiddle.net/naqE6/938/"><a href="http://jsfiddle.net">jsfiddle.net</a></a>
```

(Exemple tiré directement du forum, soit le MD problématique évoqué par sandhose)

La solution qui me parait la plus logique/simple serait de ne pas détecter les URLs automatiquement mais d'utiliser la notation `<http://google.com>` plutôt. Sachant que c'est une syntaxe assez répandue, même si ça risque d'avoir un impact assez fort sur l'existant…

**Comment by Eskimon** [comment]
Doublon de #52

**Comment by cgabard** [comment]
Oui doublon, et non pas upstream, c'est une collision entre l'algo de liens et celui de détection automatique. Je ferme ici
