### ISSUE TITLE
Liens et caractères spéciaux 

### ISSUE THREAD

**Issue by Axylium** [zestedesavoir/Python-ZMarkdown#68]
[Remonté par Holomos sur le forum](https://zestedesavoir.com/forums/sujet/3434/probleme-de-lien/) : 

> Plop,
> 
> J'arrive pas à bien utiliser ce lien dans les balises : https://fr.wikipedia.org/wiki/Compactifié_d%27Alexandrov
> 
> Quand je le fais là par exemple ça fait … autre chose qui ne passe pas.

Et effectivement dans le lien cliquable, le lien, bug.. C'est notamment dû aux caractères spéciaux je pense, car dans le premier cas le `%27` de l'url est correctement interprété, alors que dans le second cas, non !

**Comment by yapper-git** [comment]
Actuellement le parseur markdown échappe les caractères spéciaux de l'url lorsque l'on utilise la syntaxe `[texte](lien)`. Je me demande si ce comportement est vraiment souhaitable.
D'ailleurs le parseur markdown par défaut n'échappe pas les caractères spéciaux.

J'ai repéré ce comportement en voulant corriger un bug sur zds-site, voir https://github.com/zestedesavoir/zds-site/issues/2301
Le lien vers la page de profil d'un membre donné par le backend, est déjà quoté, prêt à l'emploi. C'est notamment utilisé lorsque l'on signale une typo dans un article ou un tutoriel. ZdS envoie un mail à l'auteur en mettant un lien sur le pseudo de l'auteur.
Du coup l'URL (dans le MP envoyé) est à nouveau quotée par le parseur markdown, donc doublement quoté au final. Actuellement la page de profil accepte des paramètres doublement quotés, grâce à un urlunquote (voir https://github.com/zestedesavoir/zds-site/blob/dev/zds/member/views.py#L68) à cause justement du comportement actuel du parseur markdown.

Actuellement en saisissant:

``` markdown
- https://fr.wikipedia.org/wiki/Compactifié_d'Alexandrov
- https://fr.wikipedia.org/wiki/Compactifi%C3%A9_d%27Alexandrov
- [Compactifié d'Alexandrov](https://fr.wikipedia.org/wiki/Compactifié_d'Alexandrov)
- [Compactifié d'Alexandrov](https://fr.wikipedia.org/wiki/Compactifi%C3%A9_d%27Alexandrov)
```

on obtient:

``` html
<ul>
<li>https://fr.wikipedia.org/wiki/Compactifié_d'Alexandrov</li><!-- non détecté -->
<li><a href="https://fr.wikipedia.org/wiki/Compactifi%C3%A9_d%27Alexandrov">https://fr.wikipedia.org/wiki/Compactifi%C3%A9_d%27Alexandrov</a></li><!-- OK -->
<li><a href="https://fr.wikipedia.org/wiki/Compactifi%C3%A9_d%27Alexandrov">Compactifié d'Alexandrov</a></li><!-- OK -->
<li><a href="https://fr.wikipedia.org/wiki/Compactifi%25C3%25A9_d%2527Alexandrov">Compactifié d'Alexandrov</a></li><!-- invalide -->
</ul>
```

Je trouve cela pas très cohérent d'ailleurs entre les liens automatiques et les liens manuels (avec la syntaxe `[texte](lien)`).

**Comment by cgabard** [comment]
Toute la partie sur la syntaxe `[...]()` est actuellement corrigé, il reste a uniformiser avec les liens libres.

**Comment by cgabard** [comment]
C'est maintenant corrigé de notre coté !
