### ISSUE TITLE
Problème avec les vidéos Youtube qui contiennent un « &ab_channel »

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/Python-ZMarkdown#72]
Vie le [forum](https://zestedesavoir.com/forums/sujet/4872/bug-dans-les-insertions-de-video-youtube-contenant-un-ab_channel/) : 

> En voulant intégrer une vidéo à un de mes messages, je me suis rendu compte que je pouvais intégrer l'URL suivante : `https://www.youtube.com/watch?v=1Bh4DZ2xGmw`, mais pas `https://www.youtube.com/watch?v=1Bh4DZ2xGmw&ab_channel=DestinationPr%C3%A9pa`.
> J'ai fait quelques tests, et il semble qu'on ne peut pas insérer de vidéo youtube qui contient une esperluette dans l'URL.
> 
> Ce qui m'étonne, c'est que [la regex du code source](https://github.com/zestedesavoir/Python-ZMarkdown/blob/576e34ba1d2d3b34a942b1483e858a091829ca87/markdown/extensions/video.py#L50) a l'air de fonctionner normalement, d'après regex101 : même avec l'esperluette, je catche bien ce qu'il faut. Du coup, je ne sais pas trop d'où vient le problème.
> 
> Sinon, fun fact : les URL ne sont pas reconnues par urlize.py si elles sont directement suivies d'une virgule, même si regex101 catche bien l'URL.
> Source:[melepe](http://zestedesavoir.com/forums/sujet/4872/bug-dans-les-insertions-de-video-youtube-contenant-un-ab_channel/?page=1#p90209)

**Comment by cgabard** [comment]
Maintenant corrigé !
