### ISSUE TITLE
Retours à la ligne intra-paragraphes interprétés alors qu'ils ne devraient pas

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/Python-ZMarkdown#8]
En markdown qui se respecte, une retour chariot simple n'est pas considéré comme un retour à la ligne/nouveau paragraphe.

Seul le double retour chariot (saut de ligne) doit créer un nouveau paragraphe.

**Comment by SpaceFox** [comment]
Et on peut créer un <br/> en mettant 2 espaces ou plus avant un simple saut
de ligne.

**Comment by cgabard** [comment]
En effet mais il avait été décidé au tout début de reprendre ce fonctionnement comme sur github. Comme vous voulez

**Comment by Alex-D** [comment]
Comme nohar l'a indiqué sur le sujet lié dans le forum, il vaut mieux respecter les standards afin de permettre aux auteurs de pouvoir importer sans difficulté tout texte respectant la norme.

**Comment by sedera-tax** [comment]
gvefre




ghg





ki    ki





































































fdfdd
