### ISSUE TITLE
Proposition : ajouter Landscape.io

### ISSUE THREAD

**Issue by gustavi** [zestedesavoir/Python-ZMarkdown#89]
Plus d'infos ici https://landscape.io/

Ça permet d'avoir une idée de la qualité du projet. C'est peut-être un peu ovekill mais on l'utilise pour zds et ça a permis de nettoyer pas mal le code.

**Comment by cgabard** [comment]
Il y a une conf à faire ? Car il plante magistralement pour le moment

**Comment by cgabard** [comment]
J'ai rien dit, là ça a passé, je l'ajoute
