### ISSUE TITLE
[Listes à puce] Une liste classique suivie d'une liste à puce crée une longue liste à puce

### ISSUE THREAD

**Issue by Alex-D** [zestedesavoir/Python-ZMarkdown#9]
Les listes à puce ont l'air mal isolées.

Le bug est visible ici : 
http://zestedesavoir.com/forums/sujet/1/bienvenue-sur-la-beta-de-zds?page=1#p101

Le code source du message est : 

```
- Et y a même
- des listes
- qui fonctionnent
* trop cool !

1. Donnez moi un Z
2. Donnez moi un d
3. Donnez moi un S
```

**Comment by cgabard** [comment]
Ça il me semble que c'est un bug du projet upstream plus ou moins volontaire (lié aux spec flou du mkd). Je vais essayer de corriger

**Comment by SpaceFox** [comment]
Ha, désolé mais celui-ci n'est pas corrigé.

J'obtiens un résultat du type (avec ton code source exemple :

> - Et y a même
> - des listes
> - qui fonctionnent
> - trop cool !
> - Donnez moi un Z
> - Donnez moi un d
> - Donnez moi un S

**Comment by cgabard** [comment]
@SpaceFox : Moi je ne vois pas le bug : http://zestedesavoir.com/forums/sujet/162/test

A la limite, si je vire la ligne vide entre les 2, effectivement ça transforme tout en liste non ordonnée. Mais actuellement une ligne vide permet de bien séparer les deux. Je comprend pas le bug

**Comment by SpaceFox** [comment]
Je confirme que ça foire toujours en local, je force un update du bidule et
réessaie...

**Comment by SpaceFox** [comment]
Je me suis planté, j'ai explosé mon virtualenv, je l'ai recréé, et maintenant je te confirme que la Python-ZMarkdown.git@2.4-zds.2.11 fonctionne comme prévu.

Donc je ferme :)
