### ISSUE TITLE
Parsing de jsfiddle qui déconne

### ISSUE THREAD

**Issue by Eskimon** [zestedesavoir/Python-ZMarkdown#92]
Le parseur de jsfiddle a un souci. Voici deux liens, le premier ne marche pas mais le second est OK
- https://jsfiddle.net/z5c1roLu/6/ -> Pas ok
- https://jsfiddle.net/byo71sxm/5/ -> ok

**Comment by cgabard** [comment]
Ça va être la fermeture la plus rapide de l'histoire de ce dépot, la version courante le parse correctement. Ça dut être corrigé quand j'ai refait au propre l'extension. Je viens de tester et tout semble OK.

Ce sera donc normalement sur zds dans la version 19 (la prochaine).
