### ISSUE TITLE
Pas de footnotes dans les légendes d'images

### ISSUE THREAD

**Issue by elegaanz** [zestedesavoir/Python-ZMarkdown#95]
Comme on peut le voir sur [ce message](https://zestedesavoir.com/forums/sujet/6188/valhalla/?page=1#p113162), le 1 s'affiche, mais pas en exposant et le lien n'est pas créé.

**Comment by GerardPaligot** [comment]
Pour tout ce qui est lié au parseur, merci de le faire le dépôt dédié. :)

https://github.com/zestedesavoir/Python-ZMarkdown

Je ferme ici.

**Comment by GerardPaligot** [comment]
Gros fail :D
