### ISSUE TITLE
Coloration syntaxique dans les balises info, etc.

### ISSUE THREAD

**Issue by GerardPaligot** [zestedesavoir/Python-ZMarkdown#97]
Du code cité dans une balise "information", "attention", etc ne va pas colorier le code.

**Comment by cgabard** [comment]
Heu... tu un exemple ? Je viens de tester sur zds et ça marche a priori

**Comment by GerardPaligot** [comment]
Tout à fait, voici un exemple :

`````` markdown
[[attention]]
| Tout ne fonctionne pas par magie non plus. Il existe une limitation à Gson. Pour que Gson puisse placer les valeurs dans un objet JSON, vous devez avoir des attributs dans votre classe qui correspondent aux clés spécifiées dans le fichier JSON. Dans le cas contraire, placez l'annotation `@SerializedName` sur l'attribut qui ne possède pas le bon nom avec comme paramètre à l'annotation, la valeur de la clé dans le fichier JSON. Par exemple, pour un attribut qui se nomme "nom" mais avec une clé "name" dans le fichier JSON, vous devez annoter l'attribut de la manière suivante :
| ````java
| @SerializedName("name") private String nom;
| ```
``````

**Comment by cgabard** [comment]
Ça ne devait pas marcher avant de le mettre dans le bloc.

Il faut que le nombre de tilde de début corresponde au nombre de fin. Si tu en met 4 au début, il faut en mettre 4 sur la dernière ligne (ce comportement permet d'avoir des série de tilde dans le corps du code sans que ça pose problème).

Là tu en en 3 pour terminer, et 4 pour commencer. Il doit donc prendre 3 tildes comme références et considérer ``java` comme le nom du langage.

Donc c'est pas vraiment un bug. Mais je t'accorde que c'est pas terrible. Il devrait pas accepter le tilde en début de nom de langage.

**Comment by GerardPaligot** [comment]
Oh. Bien vu.

Alors oui, la parseur devrait peut-être signalé le problème des back apostrophes mais c'est de ma faute.

Tu peux fermer si tu veux. :)

**Comment by cgabard** [comment]
Je préfère garder ouvert pour le corriger. Le parseur peut difficilement signaler quoique ce soit. Mais je pense qu'on peut considérer qu'aucun langage ne commence par ``` . Selon moi le parseur, là, ne devrait pas trouver de correspondence entre le début et la fin et donc ne pas le considéré comme un bloc de code. Ainsi celui-ci n'est pas rendu et l'auteur va vite s'en rendre compte.
