### ISSUE TITLE
Tableau MD cassé et impossible à éditer

### ISSUE THREAD

**Issue by ShigeruM** [zestedesavoir/Python-ZMarkdown#99]
On vient de me dire que le tableau MD de ce chapitre était tout cassé : https://zestedesavoir.com/tutoriels/662/debutez-en-informatique-avec-windows-8/621_internet-et-le-web/2973_le-navigateur/

Mais je ne peux pas l'éditer car j'obtiens le message d'erreur : "Une erreur est survenue dans la génération de texte Markdown. Veuillez rapporter le bug.".

**Comment by cgabard** [comment]
Hum c'est étrange... Surtout que la version actuellement en ligne ne touche pas aux tableaux. Je vérifirai si la version actuel a encre le problème.

**Comment by cgabard** [comment]
@ShigeruM : tu peux ré-essayer de l'éditer ? Je pense que ça devrait plus bugguer en tentant de l'éditer

**Comment by ShigeruM** [comment]
C'est ok, j'ai pu éditer et j'ai réparé le tableau. Merci !

**Comment by cgabard** [comment]
Cool !
